# Generated by Django 3.1.7 on 2021-05-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Viandas', 'Viandas'), ('Hortalizas', 'Hortalizas'), ('Otras Hortalizas', 'Otras Hortalizas'), ('Citricos y Frutas', 'Citricos y Frutas'), ('Granos', 'Granos')], max_length=20)),
                ('producto', models.CharField(max_length=200)),
                ('compra_productor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta_mayorista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta_minorista', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Construccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('um', models.CharField(max_length=200)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coronas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedades_de_flores', models.CharField(max_length=200)),
                ('cant_docenas', models.CharField(max_length=200, verbose_name='Cantidad de docenas')),
                ('diametro_aro', models.CharField(max_length=200, verbose_name='Diámetro del aro')),
                ('um', models.CharField(max_length=200)),
                ('precio_minorista', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('um', models.CharField(choices=[('uno', 'Uno'), ('docena', 'Docena')], max_length=10)),
                ('precio_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_3', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Topado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(choices=[('Bejucal', 'Bejucal'), ('San José', 'San José'), ('Jaruco', 'Jaruco'), ('Santa Cruz', 'Santa Cruz'), ('Madruga', 'Madruga'), ('Nueva Paz', 'Nueva Paz'), ('San Nicolás', 'San Nicolás'), ('Güines', 'Güines'), ('Melena', 'Melena'), ('Batabanó', 'Batabanó'), ('Quivicán', 'Quivicán')], max_length=20)),
                ('tramo', models.CharField(max_length=200)),
                ('km', models.IntegerField(default=0)),
                ('triciclo', models.IntegerField(default=0)),
                ('auto', models.IntegerField(default=0)),
                ('auto_y_jeep', models.IntegerField(default=0)),
                ('panel_y_micro', models.IntegerField(default=0)),
                ('camioneta', models.IntegerField(default=0)),
                ('camino', models.IntegerField(default=0, verbose_name='Camión')),
            ],
        ),
        migrations.CreateModel(
            name='Cerdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('topado_por', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.topado')),
            ],
            options={
                'unique_together': {('producto', 'topado_por')},
            },
        ),
    ]
