# Generated by Django 3.1.7 on 2021-05-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210519_1944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transporte',
            unique_together={('tramo', 'topado_por')},
        ),
    ]
