# Generated by Django 3.1.7 on 2021-05-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210526_0020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transporte',
            unique_together={('tramo', 'topado_por', 'municipio')},
        ),
    ]
