# Generated by Django 3.1.7 on 2021-05-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210526_0023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flores',
            unique_together={('descripcion', 'topado_por', 'um')},
        ),
    ]
